apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
        env: dev
    spec:
      containers:
      - name: node
        image: cloudaccelerator.azurecr.io/myapp_node
        ports:
        - name:  http
          containerPort: 3000
          protocol: TCP